[project]
name = "dailybux-server"

[mysql]
host = "dailybux.cluster-c1iigoamcpiw.ap-southeast-1.rds.amazonaws.com"
port = 13306
user = "dailybux"
password = "daily1234!"
db_name = "dailybux"

[redis]
addr = "bithop-test-outside.redis.singapore.rds.aliyuncs.com:6379"
password = "FL#OF2o9lFdfLFBPh#FDksdjf%F"

